version: "3.8"
services:
    telegraf:
        container_name: telegraf
        image: telegraf:latest
        #ports: 
        #    - "8125:8125"
        #    - "8092:8092"
        #    - "8094:8094"
        command: --config-directory /etc/telegraf/telegraf.d
        depends_on:
            - influxdb
        restart: always
        networks:
            - default
        volumes: 
            - ./etc/telegraf:/etc/telegraf
            - ./log/telegraf:/var/log/telegraf
            - /var/run/docker.sock:/var/run/docker.sock
        environment: 
            TZ: Asia/Taipei
    influxdb:
        container_name: influxdb
        image: influxdb:latest
        #ports: 
        #    - "8086:8086"
        restart: always
        volumes: 
            - influxdb-data:/var/lib/influxdb
            - ./etc/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
        environment: 
            TZ: Asia/Taipei
            INFLUXDB_ADMIN_USER: admin
            INFLUXDB_ADMIN_PASSWORD: influxdb
            INFLUXDB_HTTP_AUTH_ENABLED: 'true'
            INFLUXDB_REPORTING_DISABLED: 'true'
    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        ports: 
            - "3000:3000"
        restart: always
        volumes: 
            - grafana-data:/var/lib/grafana
            - ./etc/grafana:/etc/grafana
            - ./log/grafana:/var/log/grafana
        environment: 
            TZ: Asia/Taipei
            GF_SERVER_DOMAIN: tiunn.westus2.cloudapp.azure.com
            GF_SERVER_ROOT_URL: '%(protocol)s://%(domain)s:%(http_port)s/gf/'
            GF_SERVER_SERVE_FROM_SUB_PATH: 'true'
            GF_RENDERING_SERVER_URL: http://grafana-image:8081/render
            GF_RENDERING_CALLBACK_URL: http://grafana:3000/
            #GF_LOG_FILTERS: rendering:debug
            GF_LOG_CONSOLE_LEVEL: info
            GF_SMTP_ENABLED: 'true'
            GF_SMTP_HOST: smtp.gmail.com:465
            GF_SMTP_USER: 
            GF_SMTP_PASSWORD: 
            GF_SMTP_SKIP_VERIFY: 'true'
            GF_SMTP_FROM_ADDRESS: 
            GF_SMTP_FROM_NAME: Grafana
            GF_SMTP_EHLO_IDENTITY:
    grafana-image:
        container_name: grafana-image
        image: grafana/grafana-image-renderer:latest
        ports: 
            - 8081
        restart: always
        environment: 
            TZ: Asia/Taipei
    loki:
        container_name: loki
        image: grafana/loki:latest
        ports:
            - "3100:3100"
        restart: always
        command: -config.file=/etc/loki/local-config.yaml
        volumes:
          - ./etc/loki:/etc/loki
        environment:
            TZ: Asia/Taipei
    
volumes: 
    influxdb-data:
        name: influxdb-data
    grafana-data:
        name: grafana-data
